accelerator: cuda
benchmark: false
bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
custom_metrics: []
dataset:
  cache_load: false
  cache_save: false
  dir: ./datasets
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: Bond
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: true
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: BOTTLENECK
  label_column: none
  label_table: none
  location: local
  name: depth_3
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: bottleneck_encoder
  positional_encoding_path: false
  preprocesss_dataset: true
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  shuffle_split: true
  split:
  - 0.8
  - 0.1
  - 0.1
  split_mode: random
  task: graph
  task_type: classification
  to_undirected: false
  transductive: false
  transform: none
  tu_simple: true
  use_sparse_adj: false
devices: null
gnn:
  act: relu
  act_on_last_layer_mp: true
  agg: none
  att_final_linear: false
  att_final_linear_bn: false
  att_heads: 4
  att_heads_final: 6
  batchnorm: false
  clear_feature: true
  dilated_path_join: add
  dim_inner: 256
  dropout: 0.0
  edge_agg: add
  head: bottleneck_head
  keep_edge: 0.5
  l2norm: false
  layer_norm: true
  layer_type: ginconv_paper
  layer_type_dilated: ginconv_paper
  layers_k1: 2
  layers_k2: 2
  layers_mp: 3
  layers_post_mp: 1
  layers_pre_mp: 0
  learn_alpha_residual_connection: true
  msg_direction: single
  normalize_adj: false
  self_msg: concat
  skip_every: 1
  stage_type: skipsum
  use_edge_features: false
gpu_mem: false
mem:
  inplace: false
metric_agg: argmax
metric_best: accuracy
model:
  edge_decoding: dot
  graph_pooling: mean
  loss_fun: cross_entropy
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: dilapos_gnn
num_threads: 6
num_workers: 16
optim:
  base_lr: 0.001
  lr_decay: 0.1
  max_epoch: 100
  momentum: 0.9
  optimizer: adam
  scheduler: reduce_lr_on_plateau
  step_gamma: 0.5
  step_size: 10
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.0
out_dir: results_experiments/bottleneck_base_grid_depths_layers_small/bottleneck_base-name=depth_3-batch_size=1024-layers_k2=2-dim_inner=256
persistent_workers: false
print: both
round: 4
run_dir: results_experiments/bottleneck_base_grid_depths_layers_small
seed: 0
share:
  dim0: -1
  dim_in: 1
  dim_out: 1
  num_splits: 1
tensorboard_agg: true
tensorboard_each_run: false
train:
  accumulate_grad: 1
  auto_resume: false
  batch_size: 1024
  ckpt_clean: true
  ckpt_period: 100
  compute_test: false
  early_stopping: true
  early_stopping_patience: 50
  enable_ckpt: true
  epoch_resume: -1
  eval_period: 1
  iter_per_epoch: 32
  monitor_val: false
  neighbor_sizes:
  - 20
  - 15
  - 10
  - 5
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
  skip_train_eval: false
  walk_length: 4
train_strategy: null
val:
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
view_emb: false
