out_dir: tmp_results
num_workers: 16
metric_best: 'accuracy'
metric_agg: 'argmax'
accelerator: 'cuda'
dataset:
  format: BOTTLENECK
  name: depth_6
  task: graph
  task_type: classification
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: bottleneck_encoder
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: Bond
  preprocesss_dataset: true
train:
  batch_size: 64 #HYPER
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: dilated_gnn #[standard_gnn, dilated_gnn]
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: bottleneck_head
  layers_pre_mp: 0 
  layers_mp: 5 #when model=dilated_gnn not used, but needs to be > 0
  layers_k1: 3 #only model=dilated_gnn
  layers_k2: 2 #only model=dilated_gnn
  dilated_path_join: concat #[concat, add, none] #only model=dilated_gnn
  learn_alpha_residual_connection: true #[true, false] #only model=dilated_gnn
  layer_type: ginconv_paper #[egatconv, eginconv]
  use_edge_features: false
  layers_post_mp: 1
  dim_inner: 32 #hidden dim
  batchnorm: true
  act: relu #activation function
  act_on_last_layer_mp: false
  dropout: 0.5
  agg: none
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 10000
  scheduler: step_lr_epochs
  weight_decay: 0.0
  step_size: 1000
  step_gamma: 0.5
