out_dir: results_experiments
num_workers: 16
metric_best: 'auc'
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  node_encoder: true
  node_encoder_name: Atom
  edge_encoder: true
  edge_encoder_name: Bond
train:
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: dilated-gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  layers_pre_mp: 1
  layers_mp: 5 #not used, needs to be > 0
  layers_k1: 3
  layers_k2: 2
  use_edge_features: true 
  layers_post_mp: 1
  dim_inner: 300 #hidden dim
  layer_type: eginconv #egatconv
  stage_type: dilated-stage
  batchnorm: true
  act: relu #activation function
  dropout: 0.5
  agg: none
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 500
  scheduler: none
