accelerator: cpu
dataset:
  dir: /cluster/scratch/piattigi/datasets
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: TU
  name: NCI1
  node_encoder: false
  node_encoder_bn: false
  node_encoder_name: Atom
  preprocesss_dataset: true
  task: graph
  task_type: classification
gnn:
  act: relu
  act_on_last_layer_mp: false
  agg: none
  batchnorm: true
  dilated_path_join: add
  dim_inner: 64
  dropout: 0
  edge_agg: add
  layer_type: ginconv_paper
  layers_k1: 3
  layers_k2: 3
  layers_mp: 2
  layers_post_mp: 1
  layers_pre_mp: 0
  learn_alpha_residual_connection: true
  normalize_adj: false
  use_edge_features: false
metric_agg: argmax
metric_best: accuracy
model:
  graph_pooling: concat_across_sum_of_layers
  loss_fun: cross_entropy
  type: standard_gnn
num_workers: 8
optim:
  base_lr: 0.01
  max_epoch: 500
  optimizer: adam
  scheduler: step_lr_epochs
  step_gamma: 0.5
  step_size: 50
  weight_decay: 0.0
out_dir: results_experiments/base_grid_gin
train:
  batch_size: 32
  ckpt_period: 100
  early_stopping: true
  early_stopping_patience: 100
  eval_period: 1
  sampler: full_batch
