accelerator: cuda
dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: BOTTLENECK
  name: depth_8
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: bottleneck_encoder
  positional_encoding_path: false
  preprocesss_dataset: true
  task: graph
  task_type: classification
  use_sparse_adj: true
gnn:
  act: relu
  act_on_last_layer_mp: true
  agg: none
  batchnorm: false
  dilated_path_join: add
  dim_inner: 1024
  dropout: 0.0
  head: bottleneck_head
  l2norm: false
  layer_norm: true
  layer_type: ginconv_paper
  layer_type_dilated: ginconv_paper
  layers_k1: 2
  layers_k2: 2
  layers_mp: 3
  layers_post_mp: 1
  layers_pre_mp: 0
  learn_alpha_residual_connection: true
  normalize_adj: false
  stage_type: skipsum
  use_edge_features: false
metric_agg: argmax
metric_best: accuracy
model:
  graph_pooling: mean
  loss_fun: cross_entropy
  type: dilapos_gnn
num_workers: 16
optim:
  base_lr: 0.001
  max_epoch: 100
  optimizer: adam
  scheduler: reduce_lr_on_plateau
  step_gamma: 0.5
  step_size: 10
  weight_decay: 0.0
out_dir: results_experiments/bottleneck_base_grid_depths_2
train:
  accumulate_grad: 32
  batch_size: 64
  ckpt_period: 100
  early_stopping: false
  eval_period: 1
  monitor_val: false
  sampler: full_batch
