dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: OGB
  name: ogbg-molhiv
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Atom
  task: graph
  task_type: classification
gnn:
  act: relu
  act_on_last_layer_mp: false
  agg: none
  batchnorm: true
  dilated_path_join: concat
  dim_inner: 300
  dropout: 0.5
  layer_type: egatconv
  layers_k1: 3
  layers_k2: 3
  layers_mp: 5
  layers_post_mp: 1
  layers_pre_mp: 0
  learn_alpha_residual_connection: false
  normalize_adj: false
  use_edge_features: true
metric_agg: argmax
metric_best: auc
model:
  graph_pooling: mean
  loss_fun: cross_entropy
  type: dilated_gnn
num_workers: 16
optim:
  base_lr: 0.001
  max_epoch: 100
  optimizer: adam
  scheduler: none
  weight_decay: 0.0
out_dir: results_experiments/ogbg_molhiv_baseline_grid_design
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 1
  sampler: full_batch
